### ISSUE TITLE
Login and Sign up pages are not responsive and need more features

### ISSUE THREAD

**Issue by vedeepika** [codeisscience/journal-policy-tracker-frontend#102]
Thank you for taking the time to file a Feature Request report.

### **Issue needs to be fixed**

1). Login and sign-up pages are not responsive on mobile devices.

![IMG_20220405_191651](https://user-images.githubusercontent.com/88725279/161769078-996e1af2-2ac5-4b02-a63b-88672bb9d10f.jpg)

![IMG_20220405_191615](https://user-images.githubusercontent.com/88725279/161769129-56d5200f-8f3f-4f02-9e92-4c8f183fe0c9.jpg)

2). On large devices login and sign-up forms are not in the center.

![IMG_20220405_191532](https://user-images.githubusercontent.com/88725279/161769584-3775cb61-5240-45cb-8b9e-4c96731fd483.jpg)

![IMG_20220405_191448](https://user-images.githubusercontent.com/88725279/161769661-a6510e90-b71d-47ba-be30-00a52dc763ff.jpg)

3). I think both pages (login and sign-up page) need a heading like login form and sign-up form so users can easily identify the login page and sign-up page.

**Comment by vedeepika** [comment]
@padmajabhol Can you please review it and assign it to me?

**Comment by yochannah** [comment]
This issue looks good! @vedeepika please go ahead

**Comment by padmajabhol** [comment]
Any updates @vedeepika ?

**Comment by adityabhattad2021** [comment]
How To Contribute?

**Comment by oneknucklehead** [comment]
Is this issues still being worked upon? If not, I can work on it.

**Comment by padmajabhol** [comment]
Go ahead @oneknucklehead

**Comment by padmajabhol** [comment]
Hi @adityabhattad2021, you can look for bugs or small fixes in the code base and create an issue on your own. If it's genuine, we shall assign it to you. I hope this helps.
