### ISSUE TITLE
Hyperlinks in manifesto page opening in the same tab

### ISSUE THREAD

**Issue by prajwalkulkarni** [codeisscience/journal-policy-tracker-frontend#103]
Thank you for taking the time to file a Feature Request report.

**Is your feature request related to a problem? Please describe.**
On the manifesto page, there's a contact section beside the **How can I contribute** section that links to various contact resources. However, when these links are clicked, the user is navigated to the linked website in the same tab instead of opening a new tab. This would require the user to either manually open the links in a new tab or navigate back to the website and open contact resources one at a time. Both of which would require extra effort from the user. This practice would also deliberately navigate the user away from the application which might prevent the user from coming back and continuing browsing through the rest of the application.

**Describe the solution you'd like**
It would be a good practice to always open hyperlinks on a new tab (unless it happens to be a payment gateway or something similar), this way the user could open multiple links at once and make a decision collectively.

**Comment by prajwalkulkarni** [comment]
@padmajabhol Could you please assign this issue to me so that I can fix this UX problem?

**Comment by yochannah** [comment]
@prajwalkulkarni Thanks for thinking of this @prajwalkulkarni ! In this case, I think this is a feature that maybe we should avoid. You can read a little more here about why it's better to leave it in the control of the user whether or not it should be in another tab: https://www.nngroup.com/articles/new-browser-windows-and-tabs/

**Comment by prajwalkulkarni** [comment]
Hello @yochannah , thanks for the clarification. However, the other parts of the application (E.g footer and other sections) open up links in a new tab, hence I thought to keep the behavior consistent across the application.
