### ISSUE TITLE
Header.css Clean up

### ISSUE THREAD

**Issue by oneknucklehead** [codeisscience/journal-policy-tracker-frontend#105]
the css of the header used a lot of calculated values for its margin and setting up the button to its position in the header

**Describe the solution you'd like**
Aligning the button in the header to its position without using calculated values, but also maintaining the responsiveness of the page at the same time.

Current css:
![Screenshot 2022-04-06 131430](https://user-images.githubusercontent.com/75200954/161928026-17141b04-30e9-4da7-ad38-78903fa91b48.jpg)

working website after clean up:

https://user-images.githubusercontent.com/75200954/161930134-ab626cdc-8ebc-4cd4-98d3-a93be6945d52.mp4

**Comment by padmajabhol** [comment]
I don't think we need this for the time being.
