### ISSUE TITLE
Manifesto - Title images aligning vertically in smaller screens.

### ISSUE THREAD

**Issue by prajwalkulkarni** [codeisscience/journal-policy-tracker-frontend#109]
Thank you for taking the time to file a Bug report.

**Describe the bug**
On the manifesto page, there are two images on either side of the title, all aligned horizontally, but when the screen size is shrunk to be in a portrait mode, the title and the images are aligning vertically, also the padding is extraneous and is leaving lots of white space above and below the title.

**To Reproduce**

1. Go to the manifesto page
2. Reduce the screen size so that the window is in portrait orientation.
3. The images that were originally on either side of the title will now be aligned vertically.

**Expected behavior**
It is preferable not to show any images both above and below the title in portrait mode, as in smartphones, I feel it is important to deliver the content first. A media query can be written to hide these images below a certain breakpoint. Also removing the extra whitespace below and above the title in portrait mode can be written in the media query.
**Screenshots**
![wrap](https://user-images.githubusercontent.com/22348265/161960929-a1e785af-cc44-48ac-b1a0-ed6841405ade.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 100

**Additional context**
After a workaround, the final result would look something like this which I is believe is neat and concise.
![wrap](https://user-images.githubusercontent.com/22348265/161961153-e2978d4f-b2bd-47aa-96c3-3e77c7f67599.png)

**Comment by prajwalkulkarni** [comment]
@padmajabhol @yochannah @ikayz, May I work on this? If you feel this change makes sense and could be implemented?

**Comment by padmajabhol** [comment]
Sure, go ahead.
