### ISSUE TITLE
On clicking on logo of the site it does not redirect to homepage and the Read manifesto link does not work

### ISSUE THREAD

**Issue by Riturajrs** [codeisscience/journal-policy-tracker-frontend#110]
When on any page, clicking on the logo should take me to the home page but it does not. Instead only "#home" link is added.

**To Reproduce**
1. Click on the logo from any page
2. It does not get redirected.
3. Same is the case for Read Manifesto

**Comment by Riturajrs** [comment]
@padmajabhol can I work on this issue?

**Comment by padmajabhol** [comment]
We don't yet have a link for the manifesto part. You can work on the logo.
