### ISSUE TITLE
Fix footer hover bug

### ISSUE THREAD

**Issue by oneknucklehead** [codeisscience/journal-policy-tracker-frontend#117]
Thank you for taking the time to file a Bug report.

**Describe the bug**
the links in the footer are still clickable even when the pointer of the mouse is not directly upon the hyperlink

**To Reproduce**

1. Go to the footer section
2. hover in the area to right of the links

**Expected behavior**

**Screenshots/video demo of the problem**

https://user-images.githubusercontent.com/75200954/162013909-883d11fa-8aa2-43e1-86b5-8938fe8db53f.mp4

**Comment by Nishantjain10** [comment]
@padmajabhol I will like to work on this issue.

**Comment by padmajabhol** [comment]
@Nishantjain10 you can look for other issues, we mostly assign the issues to people who raise them.
