### ISSUE TITLE
No validators in login/signup form

### ISSUE THREAD

**Issue by Riturajrs** [codeisscience/journal-policy-tracker-frontend#118]
**Is your feature request related to a problem? Please describe.**
If I enter my email, and it is not of the proper format due to typing error or my password is not strong enough I might need to re-enter it. This degrades user experience.

**Describe the solution you'd like**
When I fill in the form I should automatically get notified whether my email is valid or not and my password is strong, and if it is not the submit button will not be activated.

**Comment by Riturajrs** [comment]
@yochannah @padmajabhol @prajwalkulkarni can I work on this issue?

**Comment by padmajabhol** [comment]
A PR has already been raised for a similar issue.
