### ISSUE TITLE
Hover functionality in navigation bar

### ISSUE THREAD

**Issue by Parth-Jain-2002** [codeisscience/journal-policy-tracker-frontend#119]
Thank you for taking the time to file a Feature Request report.

**Is your feature request related to a problem? Please describe.**
As of now, there is no hover functionality in the nav bar. Moreover, a line appears in the nav-bar below the active section, which I feel is unappealing to users. 

**Describe the solution you'd like**
1. Add hover functionality in the navbar
2. Remove the line below the active section. Instead bold the text in active section, change the background color of that cell to slightly different shade

**Additional context**

https://user-images.githubusercontent.com/72060359/162180035-4afc9e29-efec-4632-92a7-e72d44b329fa.mp4
-> Hover functionality that can be added

https://user-images.githubusercontent.com/72060359/162180453-4032c15b-2b20-4f3b-9704-0bccbf20ef2c.mp4
-> As of now, a line appears below the active section.

**Comment by Parth-Jain-2002** [comment]
@padmajabhol Can you please review this issue and if valid, assign it to me?

**Comment by padmajabhol** [comment]
I'm not sure if we need this. @ikayz can say.

**Comment by ikayz** [comment]
The line that appears on the active one is to indicate where the user is. A number of website do actually have this. And please do note that we actually did some user personas and research around the website app. The hover functionality will be added but it's a minor issue
