### ISSUE TITLE
Directly going to the link on clicking icon in contact page.

### ISSUE THREAD

**Issue by Riturajrs** [codeisscience/journal-policy-tracker-frontend#121]
**Is your feature request related to a problem? Please describe.**
On the contacts page, multiple icons are there, but the links just below it.

**Describe the solution you'd like**
I would like to link the hyperlinks directly to the picture, so when they are clicked on the person is directly directed or taken to mail section.

**Comment by Riturajrs** [comment]
@padmajabhol can I work on this?

**Comment by padmajabhol** [comment]
Sounds good but do not remove the links below the icons.

**Comment by Riturajrs** [comment]
@padmajabhol could you please review my pull request, I have done it as told to do.

**Comment by padmajabhol** [comment]
Sure!
