### ISSUE TITLE
Add form validation to contact form

### ISSUE THREAD

**Issue by padmajabhol** [codeisscience/journal-policy-tracker-frontend#123]
Currently we don't have any kind of validation for the form present in the contact page.

**Comment by padmajabhol** [comment]
@prajwalkulkarni could you like to take this up?

**Comment by prajwalkulkarni** [comment]
@padmajabhol Yeah, sure I can work on this. Could you please assign it to me?

**Comment by MoatazNasr** [comment]
can i work on this ?

**Comment by yochannah** [comment]
@MoatazNasr thanks for offering, but let's give prajwal the chance to work on this :)
