### ISSUE TITLE
the subject field on  the contact page 

### ISSUE THREAD

**Issue by Marim99** [codeisscience/journal-policy-tracker-frontend#127]
**Describe the bug**
the subject field on the contact page is a password field 

**Expected behavior**
the subject field on the contact page is a text field 

**Screenshots**
![Screenshot (218)](https://user-images.githubusercontent.com/78925756/162535751-ebc8f245-4844-4b10-b50d-74f2a725e3fe.png)

**Desktop (please complete the following information):**

- OS: [windos]
- Browser [chrome]

**Comment by Marim99** [comment]
Can you please review it and assign it to me? @padmajabhol

**Comment by yochannah** [comment]
good spot lol!

**Comment by prajwalkulkarni** [comment]
Hello @yochannah, I believe this issue is already resolved and merged (https://github.com/codeisscience/journal-policy-tracker-frontend/pull/108). @padmajabhol kindly confirm the same. Thanks.

**Comment by padmajabhol** [comment]
This has already been fixed. I'll create a new issue and assign it to you @Marim99, if that works for you?

**Comment by Marim99** [comment]
okay, it will be great 
but How do I know that the issue I found was solved before if it was not updated in the project? @padmajabhol
