### ISSUE TITLE
The journals page is not responsive on the small screen

### ISSUE THREAD

**Issue by Marim99** [codeisscience/journal-policy-tracker-frontend#128]
**Describe the bug**
The journals page is not responsive on the small screen 

**Screenshots**

https://user-images.githubusercontent.com/78925756/162537467-62664ae9-fc89-49a4-9c73-d4cb98824a21.mp4

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]

**Comment by Marim99** [comment]
Can you please review it and assign it to me?@padmajabhol

**Comment by yochannah** [comment]
hmmm, has this been fixed in any other PRs recently? we've had a few.

**Comment by padmajabhol** [comment]
I believe this has been fixed!
