### ISSUE TITLE
Redesigning the contact page

### ISSUE THREAD

**Issue by dikshashukla455** [codeisscience/journal-policy-tracker-frontend#129]
Thank you for taking the time to file a Bug report.

**Describe the bug**
There are two bugs in the contact page:

1. the color of the contact card looks bulky.
2. the contact form should be in the center.

**To Reproduce**

1. Go to the website (https://journal-policy-tracker.netlify.app/)
2. Click on the Contact link in the navbar
3. Scroll down to the contact form
4. See an error

**Actual behavior**

**Screenshots**
![Screenshot (1030)](https://user-images.githubusercontent.com/60606998/162566859-88841e06-79a9-4324-be71-c7080be11bf3.png)

**Expected behavior**
The color of the contact card should be off-white, have a slightly greyish box-shadow, and have a hover transition. The contact form should be in the middle and add a heading 'send us a message above the contact form to enhance the user's experience.
**Screenshots**
![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/60606998/162567015-6590c81b-4313-49d2-b461-5c32bdfa65bd.gif)

![Screenshot (1043)](https://user-images.githubusercontent.com/60606998/162567570-53d7aed4-f355-497a-b685-e4c150c350e7.png)

Desktop (please complete the following information):

OS: Windows 10
Browser: Chrome
Smartphone (please complete the following information):

Device: OnePlus Nord CE
OS: Android 11
Browser: Chrome

**Comment by dikshashukla455** [comment]
Greetings @padmajabhol, Can I work on this issue? If it is valid.

**Comment by padmajabhol** [comment]
Not a major ui change but could be nice to have. Do we need this @yochannah @ikayz ?

**Comment by ikayz** [comment]
@padmajabhol would be nice to have that, yes. Though the call to action bit not sure I'd have to loop in @yochannah

**Comment by yochannah** [comment]
works for me!

**Comment by dikshashukla455** [comment]
Hello everyone, I have added the PR . Kindly review it. Thank you.

**Comment by dikshashukla455** [comment]
hi  @padmajabhol, I have resent the pull request which has no merge conflicts. Kindly review it. Thank you
