### ISSUE TITLE
Home Page Image is not responsive

### ISSUE THREAD

**Issue by CoderS2020** [codeisscience/journal-policy-tracker-frontend#132]
The Home Page's first image is not responsive. It repeats on larger screens and is partially visible on small screens.

1. Go to home page
2. Go to inspect to check repsonsiveness.
3.  Beyond 1920 X 871 for 50% zoom it shows duplicate image, similarly when you decrease screen size by dragging you see image becomes partially visible.

https://user-images.githubusercontent.com/71634100/162608001-bc1afc74-bd11-4014-9978-4cba9777751f.mp4

**Expected behavior**
The image should be made responsive for different screen sizes.

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser : Google Chrome
- Version : 100.0.4896.75

**Comment by CoderS2020** [comment]
Hello, can I work on this issue?

**Comment by mjawaaad** [comment]
Hello sir, i would like to work on this issue.

**Comment by rahoolonly** [comment]
hey. I can make this responsive . Kindly give this this work to me.

**Comment by oneknucklehead** [comment]
I guess this issues has already been worked upon, please check PR #70

**Comment by padmajabhol** [comment]
The previous contributor is not really responding so assigning it to @CoderS2020

**Comment by padmajabhol** [comment]
@mjawaaad @rahoolonly you can look for bugs/small fixes and I shall assign them to you.
