### ISSUE TITLE
Navigation Bar previous active link is still active

### ISSUE THREAD

**Issue by CoderS2020** [codeisscience/journal-policy-tracker-frontend#133]
When we use the navigation bar to move from one page to another, on using the back button of the browser, the previously active page still remains active. This may confuse the user on exactly which page he/she currently is. I checked on Google Chrome as well as Microsoft Edge, both the browsers show the same error.

1. Travel some pages using navigation bar.
2. Then using the back button of browser go to previous pages.
3. You shall see that the previously active tab is still active even though we are not on that page.

Expected behavior:-
Only the current page's corresponding link/tab should be active. This will not confuse the user of current page's title.

**Screenshots**

https://user-images.githubusercontent.com/71634100/162723279-126cd380-fa5f-4809-91cc-ca74d9c77289.mp4

**Desktop**
- OS: Windows 10
- Browser : Google Chrome, Microsoft Edge

**Comment by CoderS2020** [comment]
Hello, Greetings. If this is valid ,may I work on it?

**Comment by rahoolonly** [comment]
I think if you change the effect then will work. I can do this .

**Comment by CoderS2020** [comment]
Oh, thanks for recommending., but I actually found the solution for this.

**Comment by CoderS2020** [comment]
After a lot of searching I finally found out what was wrong. To know more about it you can go through the following links:-
https://github.com/react-bootstrap/react-router-bootstrap/issues/242
https://github.com/react-bootstrap/react-router-bootstrap/issues/243

**Comment by padmajabhol** [comment]
Good catch, thankyou @CoderS2020 , but please wait for a little before a maintainer assigns you an issue.

**Comment by CoderS2020** [comment]
@padmajabhol ,extremely sorry for my impatience, will take care of that from next time.

**Comment by padmajabhol** [comment]
@CoderS2020 no worries!
