### ISSUE TITLE
Homepage button overflows

### ISSUE THREAD

**Issue by oneknucklehead** [codeisscience/journal-policy-tracker-frontend#140]
**Describe the bug**
The "read and sign the manifesto" button overflows the image element on changing the screen size.

**To Reproduce**

1. Go to [ 'journal policy tracker homepage'](https://journal-policy-tracker.netlify.app/)
2. Right Click and choose inspect element
3. try changing the dimensions of the screen

**Screenshots/Video**

https://user-images.githubusercontent.com/75200954/163171997-08c4e642-466c-44ae-b415-9254257b079e.mp4

**Comment by Mohammad-Gouse** [comment]
Can I work on this, please assign me this issue

**Comment by padmajabhol** [comment]
This has been fixed by a previous PR. Can you please pull the recent push to the repo?
