### ISSUE TITLE
login email and password validation

### ISSUE THREAD

**Issue by oneknucklehead** [codeisscience/journal-policy-tracker-frontend#143]
**Is your feature request related to a problem? Please describe.**
Currently the login/signup page accepts any password that is entered even if the length of the password is one or two letter.

**Describe the solution you'd like**
Adding regex to validate the password and making it necessary to be eight letters long and a combination of Uppercase and lowercase characters. Also, show errors if the password doesn't match the criteria instantly.

**Comment by Mohammad-Gouse** [comment]
Can I work on this, please assign it to me.

**Comment by oneknucklehead** [comment]
Hey! the issues are only assigned those who raised them for this project. This may not be the case for other projects. You can raise issues or feature requests instead.
