### ISSUE TITLE
CodeIsScience logo does'nt redirect to Home Page

### ISSUE THREAD

**Issue by Rishabhk06** [codeisscience/journal-policy-tracker-frontend#148]
**Describe the bug**
Clicking on the Code Is Science logo doesn't redirect to the home page. 

**To Reproduce**

1. Go to 'Any Page'
2. Click on 'Code is Science logo'
4. See an error

**Expected behavior**
Redirection to home page.

**Screenshots**
<img width="1432" alt="Screenshot 2022-04-18 at 10 46 15 PM" src="https://user-images.githubusercontent.com/76654144/163846211-68fbb05c-1aac-4109-82b0-f6db34cec471.png">

**Desktop (please complete the following information):**

- OS: [Mac OS]
- Browser [Chrome]

**Comment by Rishabhk06** [comment]
Please assign this issue to me so that I can do a quick fix.

> We can even remove the Home option and can rather use the logo as the Home route which would be a better UI choice.

**Comment by padmajabhol** [comment]
I think this has been fixed by a previous PR.

**Comment by padmajabhol** [comment]
Was fixed in #110
