### ISSUE TITLE
Remarks in Contact is being hidden under NavBar

### ISSUE THREAD

**Issue by Rishabhk06** [codeisscience/journal-policy-tracker-frontend#150]
**Describe the bug**
The paragraph tag in Contact section is being overlapped by NavBar and is not visible.

**To Reproduce**

1. Go to 'Contact Section'
2. See error

**Expected behavior**
The paragraph tag should be visible. Margin needs to be fixed.

**Screenshots**
<img width="1435" alt="Screenshot 2022-04-19 at 11 42 53 AM" src="https://user-images.githubusercontent.com/76654144/163938198-ecefdd8f-21fb-4385-a531-c590474a11fd.png">

**Desktop (please complete the following information):**

- OS: [Mac OS]
- Browser [Google Chrome]

**Comment by padmajabhol** [comment]
Thanks for raising this.
