### ISSUE TITLE
Contact page errors

### ISSUE THREAD

**Issue by oneknucklehead** [codeisscience/journal-policy-tracker-frontend#157]
Thank you for taking the time to file a Bug report.

**Describe the bug**
The contact page currently shows the following errors:
![Screenshot 2022-05-08 152420](https://user-images.githubusercontent.com/75200954/167291016-eb201c7d-3b28-43da-9cd7-ae839c24da53.jpg)

I believe some parts of the contact page needs clean up
**To Reproduce**

1. Go to 'http://localhost:3000/contact'
2. Right Click and then go to 'Inspect element'
3. Click on the console tab

**Comment by padmajabhol** [comment]
I'm afraid it's not the only page throwing console errors right now, could you like to take this up?

**Comment by oneknucklehead** [comment]
> I'm afraid it's not the only page throwing console errors right now, could you like to take this up?

Yeah sure!
