### ISSUE TITLE
No line break after title in manifesto section card

### ISSUE THREAD

**Issue by prajwalkulkarni** [codeisscience/journal-policy-tracker-frontend#159]
Thank you for taking the time to file a Bug report.

**Describe the bug**
On the manifesto page's "I want to express my support for the manifesto" sections, of the 3 cards, one of the cards is missing a line break after the title or the hyperlink. In the remaining two cards, either the title/link is missing or the content is missing.  This is resulting in a non-uniform interface. Firstly, the line break should be added after the title, to differentiate the title and the description clearly. Additionally, it'd be nice to have the missing title and description on the remaining two cards. 

**To Reproduce**

1. Go to the manifesto page.
2. Scroll down to the section with the title "I want to express my support for the manifesto! Tell me how".
3. Notice the 2nd card from the left where the title is not separated from the text content.

**Expected behavior**
The title/hyperlink that is acting as the title should be separated from the content by a line break, and optionally add title/description to the other two cards.

**Screenshots**
![lb](https://user-images.githubusercontent.com/22348265/167682532-b427bbe3-ca3a-410f-94f3-275b8e44bd25.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 100

**Comment by prajwalkulkarni** [comment]
@padmajabhol, May I work on this?

**Comment by padmajabhol** [comment]
Sure, if you need help coming up with an apt description for the first card, reach out on the slack channel.

**Comment by prajwalkulkarni** [comment]
Thanks. Sure, I will DM on slack now.
