### ISSUE TITLE
Install codacy to repo

### ISSUE THREAD

**Issue by ikayz** [codeisscience/journal-policy-tracker-frontend#16]
Codacy needs to be installed in the repo, more on [Codacy](https://www.codacy.com/)

**Comment by dikshashukla455** [comment]
@ikayz, Can I work on this issue? If you allow me?

**Comment by yochannah** [comment]
@dikshashukla455 go for it, let us know if we need to help or enable anything!

**Comment by dikshashukla455** [comment]
Sure, I will work on it

**Comment by dikshashukla455** [comment]
@ikayz @yochannah  Codacy wants $15 for getting started after the 14-day free trial. So, what do you suggest that I do?

**Comment by ikayz** [comment]
Yeah, for personal use you have to subscribe. It's free for open source projects. It requires admin rights I think to a repo. I'll take care of this issue since I have admin rights

**Comment by dikshashukla455** [comment]
Okay ! so, I will look for another issue?
