### ISSUE TITLE
Autocomplete input fields

### ISSUE THREAD

**Issue by oneknucklehead** [codeisscience/journal-policy-tracker-frontend#160]
Thank you for taking the time to file a Bug report.

**Describe the bug**
Currently the console shows that some of the input fields need an autocomplete attribute.

**To Reproduce**

1. Go to '/login' or'/signup
2. Right Click anywhere on the screen
3. click on inspect element
4. see the errors in the console section

**Screenshots**

![Screenshot 2022-05-12 150759](https://user-images.githubusercontent.com/75200954/168041039-47677af1-5fcb-4eea-b3c7-4d5844b83fdd.jpg)

![Screenshot 2022-05-12 150735](https://user-images.githubusercontent.com/75200954/168041051-573643e7-8d4e-4d93-9d49-32410e6cb3d3.jpg)

**Desktop (please complete the following information):**

**Comment by padmajabhol** [comment]
Thanks for pointing this out.
