### ISSUE TITLE
The navbar content is on extreme left

### ISSUE THREAD

**Issue by sanjayk0508** [codeisscience/journal-policy-tracker-frontend#180]
Content is on extreme left in hamburger menu (mobile view) Navbar content should be centered

**Comment by arsh331** [comment]
Hello, I made the required changes and would like to make a pull request.

**Comment by sanjayk0508** [comment]
Hey Arsh, I don't have the authority to make a PR. I just saw an issue and informed it.

**Comment by arsh331** [comment]
Ok I see, Thank you though

**Comment by vishudhiman** [comment]
Hey, can I work on this?
