### ISSUE TITLE
Add website preview

### ISSUE THREAD

**Issue by yochannah** [codeisscience/journal-policy-tracker-frontend#19]
This could be Netlify or the other one that @CIPHERTron  suggested... what was that again?

**Comment by CIPHERTron** [comment]
@yochannah , It was Feature Peek but there's a bad news. Netlify acquired Featurepeek and it kinda removed its existence completely XD
Previously, it was at https://featurepeek.com/ but now, its redirecting to https://netlify.com
But no worries, netlify's preview is also great and easy to configure or you can say, it requires 0 configuration.

**Comment by yochannah** [comment]
ah lol - everything comes down to Netlify in the end 😂

**Comment by yochannah** [comment]
this is live at https://journal-policy-tracker.netlify.app/
