### ISSUE TITLE
Bug: make Premise section more responsive for smaller screens.

### ISSUE THREAD

**Issue by padmajabhol** [codeisscience/journal-policy-tracker-frontend#200]
**Describe the bug**
Currently, the particular component is not fully responsive.

**To Reproduce**
1. Go to the homepage
2. Scroll down to Precise section and open dev tools

**Screenshots**
<img width="1440" alt="Screenshot 2022-10-07 at 9 58 13 PM" src="https://user-images.githubusercontent.com/75530516/194604215-ae2df987-75e9-4b60-9fbd-357e47a222d5.png">

**Comment by Anish-Sarawgi** [comment]
Can i work on this issue?

**Comment by blyncnov** [comment]
Can I work on This issue  as well?

**Comment by padmajabhol** [comment]
> Can I work on This issue as well?

We are assigning just one person per issue.
