### ISSUE TITLE
Bug: Third grid on homepage needs to be more responsive

### ISSUE THREAD

**Issue by padmajabhol** [codeisscience/journal-policy-tracker-frontend#201]
**To Reproduce**

1. Go to homepage
2. Scroll down to third section

**Screenshots**
<img width="1440" alt="Screenshot 2022-10-07 at 9 58 22 PM" src="https://user-images.githubusercontent.com/75530516/194605011-7d8f88f5-c4ec-464d-8721-d583a315770a.png">

**Comment by horizenight** [comment]
Can I work on This issue ?

**Comment by horizenight** [comment]
Please give the review :


![hacktoberfestbug1](https://user-images.githubusercontent.com/76839614/194622135-b65a4595-6991-4482-9c47-255cec4a7d95.gif)
