### ISSUE TITLE
update favicon and page title

### ISSUE THREAD

**Issue by yochannah** [codeisscience/journal-policy-tracker-frontend#21]
right now it's default React boilerplate: 
<img width="83" alt="react icon and the word 'react'" src="https://user-images.githubusercontent.com/9271438/125796835-4337a61b-b984-4fcf-9b54-2c6bf5fdb783.png">

**Comment by ikayz** [comment]
The page title and favicon have been updated, changes in PR.

**Comment by ikayz** [comment]
@yochannah this issue has been fixed
