### ISSUE TITLE
hover effect on header button 

### ISSUE THREAD

**Issue by harshit-paneri** [codeisscience/journal-policy-tracker-frontend#211]
Hover Effect on Header Button
Type of Hover Effect : Zoom In Hover effect
Try to add file in CSS on landing page with transform function 👩🏻‍💻

**Comment by harshit-paneri** [comment]
Hey @padmajabhol Can you please assign me this issue

**Comment by yochannah** [comment]
hmmm, I think it might be good to see this before we promise to merge, but please do go ahead and take a stab at it, @harshit-paneri !

**Comment by harshit-paneri** [comment]
I did Little zoom effect : [zoom_effect_video](https://drive.google.com/file/d/1MzPNNBIPjoTkJfct7YDXKbyWS03DL75U/view?usp=sharing)
Please check this video @yochannah

**Comment by padmajabhol** [comment]
Hi @harshit-paneri, sorry for the delay and thanks for opening this, but we encourage people to help us understand what they intend to do before attempting and opening an PR. It could either be through visuals or figma representations?

**Comment by harshit-paneri** [comment]
Hi @padmajabhol , I also send video with PR , you can visit it for visuals . 
zoom effect : [zoom_effect_video](https://drive.google.com/file/d/1MzPNNBIPjoTkJfct7YDXKbyWS03DL75U/view?usp=sharing)
