### ISSUE TITLE
Frontend - Dashboard improvement 

### ISSUE THREAD

**Issue by harshit-paneri** [codeisscience/journal-policy-tracker-frontend#221]
## Dashboard improvement 
Hello , I just want to know is there is any change required in the dashboard part, because there is white space in this

Browser : All Browser
Issues Related : Frontend
Page : Dashboard

![image](https://user-images.githubusercontent.com/82382478/208886623-a6f43084-b212-43de-b574-f4f7ee2974d1.png)

**Comment by khushigarg1** [comment]
Can you assign this issue to me ?

**Comment by harshit-paneri** [comment]
> Can you assign this issue to me ?

Hey @khushigarg1 , I am not the owner of this repo
