### ISSUE TITLE
Routing should work for direct page links

### ISSUE THREAD

**Issue by yochannah** [codeisscience/journal-policy-tracker-frontend#27]
e.g. on the netlify preview, I have to remove contact for this link to work: 

https://deploy-preview-26--journal-policy-tracker.netlify.app/contact

**Comment by afzal442** [comment]
hello Yo, can I work on this?

**Comment by ikayz** [comment]
@afzal442 you can work on this

**Comment by yochannah** [comment]
Thanks Afzal - once you're ready please make a PR or let us know if you have any Qs!

**Comment by afzal442** [comment]
that's gr8. So what I understood is we have to remove the `contact` route from the navbar. Else, could you be more explicit on this?

Thanks.

**Comment by yochannah** [comment]
@afzal442 not quite - basically, right now the routing works when you click on the links in the site, but if you copy/paste a link that has a path (e.g. /contact), we get a "page not found" error. So the goal is to make sure that even if we have a link to a specific page, that the links work and takeyou to the correct page.

**Comment by afzal442** [comment]
Thanks @yochannah! 

On my local machine, it works properly. But I tried to figure out its solution to this issue.

I have added `<Redirect to="/" />` to ` index.js`. Maybe this can fix the link issue else, we have to look upon some other options. To test it on `netlify.app` deployment I have to make a PR for this.

**Comment by yochannah** [comment]
fixed by #28
