### ISSUE TITLE
User management dashboard

### ISSUE THREAD

**Issue by ikayz** [codeisscience/journal-policy-tracker-frontend#33]
Create a user management dashboard

**Comment by ikayz** [comment]
@padmajabhol this is the issue that we can discuss and start working

**Comment by padmajabhol** [comment]
> @padmajabhol this is the issue that we can discuss and start working

Sure, I first need to understand what all we need in the management dashboard and plan the UI accordingly.

**Comment by ikayz** [comment]
@padmajabhol sure thing.

**Comment by yochannah** [comment]
- change password, change email - individual users
- Admin dashboard: remove / add users, raise priveleges from normal user to admin and back

**Comment by yochannah** [comment]
we also need a sketch/figma of what the UI might look like. Assigning this to either @yochannah or @ikayz

**Comment by ORKO06** [comment]
@yochannah I would like to work on this if no one is working currently on it. I can also develop the UI if it's not available.

**Comment by padmajabhol** [comment]
Hi @ORKO06 , the organization has proposed this as a part of gsoc'22 and we don't yet have the prototype. Meanwhile you can have a look at other issues.
