### ISSUE TITLE
Processing mark down

### ISSUE THREAD

**Issue by ikayz** [codeisscience/journal-policy-tracker-frontend#34]
Add markdown processing for the blog.

**Comment by ORKO06** [comment]
@ikayz 
Can you elaborate on this issue a little more?

**Comment by yochannah** [comment]
@ORKO06 the idea behind this one is that right now the blog pages wouldn't convert markdown to HTML - it'd output as plain text. We'd prefer to convert the markdown into HTML instead!

**Comment by ikayz** [comment]
@ORKO06 what @yochannah has elaborated is the idea behind this issue

**Comment by ORKO06** [comment]
Okay, I am currently having my exams. After a week they will end, then I will start working on this issue.
