### ISSUE TITLE
User routing - Login

### ISSUE THREAD

**Issue by ikayz** [codeisscience/journal-policy-tracker-frontend#37]
Routing users to Login after sign up

**Comment by parth270** [comment]
do I have to just route to login ??
that is a pretty easy task

**Comment by ikayz** [comment]
@parth270 Yes, pretty much that

**Comment by roshanchatei** [comment]
> @parth270 Yes, pretty much that

So, I just did that
we need the backend to to check for successful signup

**Comment by ikayz** [comment]
Actually the issue needs to be updated as we had discovered issues when signing up.

**Comment by ikayz** [comment]
@parth270 did you ever attempt this issue?

**Comment by parth270** [comment]
> @parth270 did you ever attempt this issue?

Yes sir I did it!!

**Comment by parth270** [comment]
sorry for replying late!!,
should I make a pull request??

**Comment by ikayz** [comment]
@parth270 someone is already working on it.

**Comment by ikayz** [comment]
@roshanchatei is working on it

**Comment by parth270** [comment]
okk suree no problem!!
