### ISSUE TITLE
Setup ES-Lint and Prettier for the project

### ISSUE THREAD

**Issue by padmajabhol** [codeisscience/journal-policy-tracker-frontend#43]
This will help us to maintain standard coding conventions throughout the project.

**Comment by CIPHERTron** [comment]
Heyy @ShreyaPrasad1209 first of all, I appreciate your contributions. Thank you for that but I'm afraid I can't review your PR since it was already assigned to @padmajabhol and she was already working on it.

Generally, we prefer to leave issues to the assignee unless it's obviously been a long time since they last worked on it. 

Would you mind picking up any other issue? Thanks again for your contributions!

**Comment by ShreyaPrasad1209** [comment]
@CIPHERTron thank you for getting back! I opened a PR before the assignee and I have spent considerable time on it if you take a look at it. It would be great if you could at least look over, it would motivate me to contribute more to this project 😊

**Comment by CIPHERTron** [comment]
> @CIPHERTron thank you for getting back! I opened a PR before the assignee and I have spent considerable time on it if you take a look at it. It would be great if you could at least look over, it would motivate me to contribute more to this project blush

Sure thing. Let me just check if @padmajabhol is okay with it.

Also, since you both have worked on the same issue, it would be great if @padmajabhol could review PR #45 🙂

**Comment by padmajabhol** [comment]
> > @CIPHERTron thank you for getting back! I opened a PR before the assignee and I have spent considerable time on it if you take a look at it. It would be great if you could at least look over, it would motivate me to contribute more to this project blush
> 
> Sure thing. Let me just check if @padmajabhol is okay with it.
> 
> Also, since you both have worked on the same issue, it would be great if @padmajabhol could review PR #45 🙂

Yeah sure, since she sent a PR before I did, it's absolutely okay. You can review it as well. I ll be looking out for more issues in the future 😄

**Comment by parth270** [comment]
Hello everyone!!
I am Parth and I am contributing to an open source project for the first time,
can anyone tell  me how can I work on this issue, it would be great to get some help 😇😇

**Comment by roshanchatei** [comment]
@yochannah  I have made a PR to fix this issue, can you check it?
