### ISSUE TITLE
[REFACTOR] Arrange files into a structured directory system

### ISSUE THREAD

**Issue by CIPHERTron** [codeisscience/journal-policy-tracker-frontend#44]
As of now, we don't have a specific file structure. It would be more organized if we could just structure the directories. For instance, we could group the files into:
- styles [will contain all the styles]
- components [will contain all UI components]
- screens [will contain all the pages]
- utils [will contain all the helper functions or custom hooks]
- static [will contain all the static assets]
- config [will contain all the texts that goes into the website so that we don't have to search the whole codebase to change the content]

**Comment by parth270** [comment]
can I work on this issue if no one is working on this??

**Comment by padmajabhol** [comment]
I guess this issue can be closed.
