### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by roshanchatei** [codeisscience/journal-policy-tracker-frontend#51]
For larger screen sizes the footer is not at the bottom
![Code is Science - Brave 1_27_2022 3_50_42 PM](https://user-images.githubusercontent.com/83601217/151340465-39e73506-5de8-4dca-b547-847e947d886b.png)
.

**Comment by ikayz** [comment]
@roshanchatei that's well noted. Please, when opening issues. Explain what the issue is. Issue titles should not be vague.

**Comment by ikayz** [comment]
@roshanchatei do look at our development codebase as it's ahead of the master
