### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by roshanchatei** [codeisscience/journal-policy-tracker-frontend#52]
The navbar should take the entire width of the screen
![Code is Science - Brave 1_27_2022 3_50_12 PM](https://user-images.githubusercontent.com/83601217/151341043-c3038992-8956-48fb-935b-36b076004a29.png)
.

**Comment by ikayz** [comment]
This issue is not properly explained.

**Comment by yochannah** [comment]
Hey @roshanchatei, thanks for logging these issues! I have a couple of links here which have some tips for creating a really good github issue - please do take a read through! 

- https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f 
- https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612

In particular, in this case: How does one reproduce the bug you've reported? It would be great to know: 

1. what browser you're using, and if it occurs in other browsers.
2. what you'd expect to happen. 
3. what actually happens.
4. How I (as an issue reader) can reproduce the bug if I want to try to fix it or revew the bug myself.
