### ISSUE TITLE
Pages are not responsive.

### ISSUE THREAD

**Issue by roshanchatei** [codeisscience/journal-policy-tracker-frontend#53]
Tablet view
![Code is Science - Brave 1_27_2022 4_06_07 PM](https://user-images.githubusercontent.com/83601217/151342596-06501881-6967-45e2-bda3-8f00db5ba268.png)

**Comment by roshanchatei** [comment]
Mobile view
![Code is Science - Brave 1_27_2022 4_06_19 PM](https://user-images.githubusercontent.com/83601217/151342633-5c1a5d5f-935d-44f6-ae39-a62a254bccfe.png)

**Comment by ikayz** [comment]
By pages, is it all pages or the one specific in the screenshot?

**Comment by roshanchatei** [comment]
> By pages, is it all pages or the one specific in the screenshot?

all pages, should I attach all pages screenshots?

**Comment by ikayz** [comment]
Okay, sure

**Comment by roshanchatei** [comment]
> Okay, sure
![Code is Science - Brave 1_27_2022 10_08_43 PM](https://user-images.githubusercontent.com/83601217/151403631-9c5c141e-c926-4bdc-83d0-c6c869d98e3e.png)

![Code is Science - Brave 1_27_2022 10_09_12 PM](https://user-images.githubusercontent.com/83601217/151403642-8efe373f-d602-4386-a75b-3d97d3918ad4.png)

![Code is Science - Brave 1_27_2022 10_09_24 PM](https://user-images.githubusercontent.com/83601217/151403669-d70d8e6d-7dcd-4fab-8740-5dbf4f558ed7.png)

**Comment by roshanchatei** [comment]
contact and journal are responsive and the rest are not.

**Comment by ikayz** [comment]
Hi thanks for the work on this. You can work on the responsiveness and please target 400px as the minimum screen screen size and/or width. Majority of our target audience based on the personas will most likely have smartphones.

**Comment by roshanchatei** [comment]
> Hi thanks for the work on this. You can work on the responsiveness and please target 400px as the minimum screen screen size and/or width. Majority of our target audience based on the personas will most likely have smartphones.

ok, I will start working on this after 2-3 days after my exams get over.

**Comment by ikayz** [comment]
@roshanchatei alright, thanks. We'll try to fix what we can until then

**Comment by roshanchatei** [comment]
> @roshanchatei alright, thanks. We'll try to fix what we can until then

don't worry, I will be back in 2-3 days. until then you can work on some issues.

**Comment by parth270** [comment]
I am done with this issue!!
should I make a PR ??

**Comment by parth270** [comment]
I made a PR can you check that out??
@ikayz

**Comment by parth270** [comment]
are the pages responsive now??
have you checked my commits??? @ikayz ??

**Comment by VishalPatil18** [comment]
Hey @padmajabhol can I work on this issue so that I could include it in my proposal for GSoC'22?

**Comment by adityabhattad2021** [comment]
Hey can I work on this issue?
