### ISSUE TITLE
Journal Table page showing bad data

### ISSUE THREAD

**Issue by erik-whiting** [codeisscience/journal-policy-tracker-frontend#62]
**Describe the bug**
The page on https://codeisscience.com/journal_table/ seems to have a bug. Maybe it's just me or maybe there isn't any data in the database yet, but the page itself looks like it's returning bad data.

Sorry if this has been reported already, or if I'm using the website wrong. If this is a real bug, I'm happy to help with it if no one else is on it already.

**To Reproduce**

1. Go to https://codeisscience.com/
2. Click on "Open Source Journals" in the top right corner
3. See error

**Expected behavior**
I assume that after I click the link, I would see a list of open source journals.

**Screenshots**
I'm on Windows 10 and using Google Chrome.

Here's what the page looks like:
![image](https://user-images.githubusercontent.com/47164199/160270609-5c4d4f02-e5eb-40ed-9aad-9a13e2514b77.png)

Smaller screenshot showing the weird data being returned:
![image](https://user-images.githubusercontent.com/47164199/160270731-7141291f-f574-4eb3-bc89-fda0ce2506fe.png)

Here are the errors in the JavaScript console:
![image](https://user-images.githubusercontent.com/47164199/160270701-a42c8007-c4c5-40a5-8115-757bce65c4bd.png)

**Comment by padmajabhol** [comment]
I believe this has to do with the backend. Can you reference this issue in our backend repository?

**Comment by erik-whiting** [comment]
hey @padmajabhol thanks for responding! I did open a new issue [here](https://github.com/codeisscience/journal-policy-tracker-backend/issues/42) and opened a PR for it as well [here](https://github.com/codeisscience/journal-policy-tracker-backend/pull/46). Thanks!

**Comment by CIPHERTron** [comment]
Heyy @erik-whiting thanks for opening the issue but the above-mentioned issue is related to [this](https://github.com/codeisscience/code-is-science) repository because that's where the `codeisscience.com` website development takes place. I haven't worked on that project but I think @yochannah can help here :D

**Comment by erik-whiting** [comment]
Closing this because it should have been reported in another repo. New issue is [here](https://github.com/codeisscience/code-is-science/issues/98).
