### ISSUE TITLE
Hero section in homepage is not responsive

### ISSUE THREAD

**Issue by ORKO06** [codeisscience/journal-policy-tracker-frontend#63]
Thank you for taking the time to file a Bug report.

**Describe the bug**
If you visit the homepage and then inspect it then on a screen less than 1200px width the Read and Sign the manifesto button is not made responsive as its margin-left is given 60em.

**To Reproduce**
To give the margin-left property a responsive value which should be applicable for all screen sizes.

1. Go to '[https://journal-policy-tracker.netlify.app/](https://journal-policy-tracker.netlify.app/)'
2. Right-click the mouse button and then click on  'inspect '
3. Keep the dimension responsive and make the screen size less than 1200 px.
4. See an error.

**Expected behavior**
The button should always lie in between the image space for the entire screen width

**Screenshots**
![image](https://user-images.githubusercontent.com/74568847/160749721-ca3f41fc-b596-4cc0-87e1-b3c448d392ae.png)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [Brave]

**Comment by yochannah** [comment]
Thansk for spotting this @ORKO06 !

**Comment by ORKO06** [comment]
I would like to work on this and fix it.

**Comment by yochannah** [comment]
thanks!
