### ISSUE TITLE
Typo mistake in the readme

### ISSUE THREAD

**Issue by ORKO06** [codeisscience/journal-policy-tracker-frontend#64]
Thank you for taking the time to file a Bug report.

**Describe the bug**
In the readme, it is written Journal Policy Tracker Backend.

**To Reproduce**
Edit the readme file and change the text to Journal Policy Tracker Frontend.

**Screenshots**
![image](https://user-images.githubusercontent.com/74568847/160751085-ef474618-e486-4386-b5a4-d40ee25b80fc.png)

**Comment by yochannah** [comment]
Please go ahead and make a PR to fix it! :)
