### ISSUE TITLE
Signup page bottom whitespace and signup card is not in the center for some screen sizes

### ISSUE THREAD

**Issue by ORKO06** [codeisscience/journal-policy-tracker-frontend#68]
Thank you for taking the time to file a Bug report.

**Describe the bug**
There is some white space at the bottom which does not appear good. Also for some screen sizes, the signup card is not in the center.

**To Reproduce**

1. Go to '[https://journal-policy-tracker.netlify.app/signup]((https://journal-policy-tracker.netlify.app/signup))'
2. Check the bottom whitespace and for some screen sizes the signup card is not in the center.

**Expected behavior**
There should be no bottom whitespace and the signup card should be in the center for all possible screen sizes.

**Screenshots**
![image](https://user-images.githubusercontent.com/74568847/161141175-21afdb6e-07c6-4186-a731-e6cbe60bbda3.png)

**Comment by ORKO06** [comment]
I am working on this.

**Comment by padmajabhol** [comment]
I'm not sure if this is needed. @ikayz your thoughts on this?

**Comment by padmajabhol** [comment]
#126
