### ISSUE TITLE
Background image gets cropped out when screen size is varied

### ISSUE THREAD

**Issue by predator4hack** [codeisscience/journal-policy-tracker-frontend#69]
Thank you for taking the time to file a Bug report.

**Describe the bug**
Background image in the header is not responsive. Also the header button overflows the header section.

**To Reproduce**

1. Go to [journal_policy_tracker_app](https://journal-policy-tracker.netlify.app/)
2. Right-click the mouse button and then click on 'inspect '
3. Set the dimentions to 'Responisve'  and decrease the window size to 800px.

**Expected behavior**
The background image in the header should not get cropped when changing the screen size and the button should be inside of the header section.

**Screenshots**
![Error](https://lh3.googleusercontent.com/pw/AM-JKLVG7Av83kllLzosoQoL-VpZylN52SaJshbadd5jSBe9z0CFMpi1MtCrRLDe5NaJqnsGZi5374y2arnPjuUE5Xk-agCNX8wQF4r0WQ8k-h6cwbKbeuSNgdmQqd3EPEdMs7sL-e8ZVLA8e6rEouQrNVBU=w1840-h936-no?authuser=0)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser Chrome
- Version 99

**Comment by ORKO06** [comment]
I have already sent a pr for this issue. Hope you can take some new issue.

**Comment by padmajabhol** [comment]
HI, please wait for the maintainers to assign you an issue before you make a PR for it. Sometimes, we might not want a particular change proposed in an issue. In such a case, we don't want the contributor's work to go in vain.

**Comment by predator4hack** [comment]
Hi @padmajabhol , thanks for your comments. I'll take care of this next time :)
