### ISSUE TITLE
Improving Manifesto page's layout

### ISSUE THREAD

**Issue by Tanish2000** [codeisscience/journal-policy-tracker-frontend#74]
**Is your feature request related to a problem? Please describe.**
When I visited the manifesto's page, I saw that the layout of the page was not that good and that ruined the user experience.

**Describe the solution you'd like**
I have changed the layout of the page a little and I want to change the complete layout of the page to improve UX. I have attached a screenshot below with the new changes as an idea.  

Please assign this issue to me @yochannah , @JPTIZ .

**Screenshots**

Previous

![Screenshot (23)](https://user-images.githubusercontent.com/68784397/161391781-f423c22d-5492-49e6-b02f-10bad3123337.png)

After some changes

![Screenshot (24)](https://user-images.githubusercontent.com/68784397/161391805-a841b21a-363d-47be-8d53-b231ba085006.png)

In this way, the layout can be changed to improve the user experience.

**Comment by Tanish2000** [comment]
I want to work on this.

**Comment by ikayz** [comment]
Oh, okay. Thanks for the fix we do have a design we are referencing. @yochannah what's your say on this?

**Comment by Tanish2000** [comment]
Please review my PR  @ikayz @yochannah , so I can move forward with further changes if needed.

**Comment by Tanish2000** [comment]
Can you please share the referenced design if possible @ikayz ?

**Comment by yochannah** [comment]
Looking good!
