### ISSUE TITLE
Inconsistent codebase

### ISSUE THREAD

**Issue by NumanAnees** [codeisscience/journal-policy-tracker-frontend#75]
**Describe the bug**

Codebase is not consistent. Login.js is a React **class component** while all other components in the codebase are React **functional components**.

**Expected behavior**

Whole codebase should be **consistent**. Either use React functional component or React class component. Otherwise it will become difficult for the developer to manage the codebase in **future**.

**Screenshots**

![login](https://user-images.githubusercontent.com/67089723/161392648-66c96808-579f-4a0b-bf82-7dc0450afdda.png)

**Comment by padmajabhol** [comment]
Thanks for pointing this out. We are looking out to convert all class-based components to functional ones. Could you like to take this up?

**Comment by NumanAnees** [comment]
@padmajabhol Yeah sure, Please assign this to me.

**Comment by NumanAnees** [comment]
@padmajabhol Yeah sure, Please assign this to me 👍🏻
