### ISSUE TITLE
Validation required for Journal and Login / Signup Components

### ISSUE THREAD

**Issue by NumanAnees** [codeisscience/journal-policy-tracker-frontend#76]
**Describe the bug**

Journal and Login/Signup components required some basic validations. User **should not** be able to submit forms with empty fields or no data.

**To Reproduce**

Submit form with no data.

**Expected behavior**

We should validate data in both client and server sides for better performance. It is a **costly** process to submit invalid data from frontend to backend and generating error message from backend.

**Alert Issue**

Instead of these JavaScript 's simple alerts we should code better alerts using **CSS or bootstrap** for better user experience.

**Screenshots**

https://user-images.githubusercontent.com/67089723/161393834-66cd9565-b573-4cc6-a845-2bd68eb4cb5c.mp4

**Comment by vedeepika** [comment]
Can I work on this issue?

**Comment by padmajabhol** [comment]
Hi @NumanAnees , it's a good practice to wait for maintainers to assign you an issue before you open a PR for it.

**Comment by ikayz** [comment]
@NumanAnees please exercise patience and wait for maintainers like @padmajabhol has pointed out before making a PR.

**Comment by NumanAnees** [comment]
@ikayz @padmajabhol thanks for guiding me and sorry for inconvenience from my side. Can you please assign it to me so that I can make a separate PR only for this issue?

**Comment by NumanAnees** [comment]
PR merged...
