### ISSUE TITLE
Footer - Copyright year is hardcoded

### ISSUE THREAD

**Issue by prajwalkulkarni** [codeisscience/journal-policy-tracker-frontend#80]
Thank you for taking the time to file a Bug report.

**Describe the bug**
The current code uses statically typed copyright year "2021 Code is science", which requires updating the year manually every year.
Instead, the year could be dynamically updated using JavaScript's `Date` object.
**To Reproduce**

1. Go to Homepage or any page
3. Scroll down to Footer
4. Inspect the footer, you can observe that the year is hardcoded

**Expected behavior**
The copyright year should be updated automatically to the current running year.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 99.0.4844.84

**Smartphone (please complete the following information):**

**Additional context**

**Comment by padmajabhol** [comment]
Thanks for pointing this out.

**Comment by prajwalkulkarni** [comment]
@padmajabhol I've linked to a PR that fixes this issue, could you kindly review it? Thanks.
