### ISSUE TITLE
Unit testing react components

### ISSUE THREAD

**Issue by predator4hack** [codeisscience/journal-policy-tracker-frontend#81]
Thank you for taking the time to file a Feature Request report.

**Is your feature request related to a problem? Please describe.**
As developers continue to add new features and solve bugs, it's critical to ensure that no other code is broken as a result of the changes. Unit testing can aid in these situations.

Major benifits of unit testing:
- improving application architechture and maintainability
- provide a quick feedback on the changes made by developers

**Describe the solution you'd like**
Rendering component trees in a simplified test environment and asserting on their output.

**Additional context**
[React testing using Jest and React testing library](https://reactjs.org/docs/testing.html)

**Comment by predator4hack** [comment]
@padmajabhol @ikayz @yochannah can I work on this issue?

**Comment by padmajabhol** [comment]
Hi, I don't think if we should go for any kind of testing right now. Although, once we have the website up and running, I could prefer going for a core E2E testing with Cypress and then integrating it with the CI.
Your thoughts on this @ikayz @yochannah ?

**Comment by ikayz** [comment]
I agree with @padmajabhol. We should have tests once the website is up and running.
