### ISSUE TITLE
Navbar - Focusing on search bar causes incomplete outline

### ISSUE THREAD

**Issue by prajwalkulkarni** [codeisscience/journal-policy-tracker-frontend#83]
Thank you for taking the time to file a Bug report.

**Describe the bug**
The search bar present in the navigation bar is composed of primarily two elements, an input field, and a logo. The logo is placed at the right end of the input field. When the search bar is focused, by default an outline is drawn by the browser, since adding an outline on focus is a default behavior to an input field and not a logo, focusing on the search bar outlines only the input field, giving it an inconsistent look in the focused state.

**To Reproduce**

1. Go to the Homepage or any route.
2. Look up to the nav bar at the top
3. Click on the search bar.
4. The outline is added only to the input field and not the search logo.

**Expected behavior**
The outline should be added to both the input field and the logo, or to neither of them on focus, of which the latter gives a better UX and consistent UI.

**Screenshots**
![footer](https://user-images.githubusercontent.com/22348265/161415970-4b5ac8b6-75b3-4096-842d-dfc6f35caae0.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 99.0.4844.84

**Smartphone (please complete the following information):**

- Device: Redmi Note 7
- OS: Android
- Browser Chrome
- Version 97.0.4692.87

**Additional context**

**Comment by prajwalkulkarni** [comment]
@padmajabhol @ikayz @yochannah, could you please assign this issue to me, I'd like to work on this and get it fixed.

**Comment by padmajabhol** [comment]
Hi, this issue has already been solved #61
