### ISSUE TITLE
Header - Warning: No value passed to prop "fluid"

### ISSUE THREAD

**Issue by prajwalkulkarni** [codeisscience/journal-policy-tracker-frontend#85]
Thank you for taking the time to file a Bug report.

**Describe the bug**
The header section on the homepage (/) consists of a button component within the `Jumbotron` component. A prop `fluid` is passed to the button component. However, no value is passed to this prop, this defaults to `true` but isn't written to the DOM, this is throwing a warning in the console of the browser's dev tools. Such errors could stop the website from being built for production in the future.

**To Reproduce**

1. Go to Homepage
2. Inspect the page
3. Click on the console tab of the dev tools
4. A warning message can be seen.

**Expected behavior**
As the warning suggests, a value needs to be passed to this prop
```
If you want to write it to the DOM, pass a string instead: fluid="true" or fluid={value.toString()}.
```

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 99

**Smartphone (please complete the following information):**

**Additional context**

**Comment by prajwalkulkarni** [comment]
@padmajabhol, Looked through the existing and closed issues, this hasn't been addressed yet. Can I take this up?

**Comment by padmajabhol** [comment]
Go ahead.

**Comment by prajwalkulkarni** [comment]
Linked a PR, kindly review.
