### ISSUE TITLE
"Read and Sign the manifesto" button overflow in the mobile view

### ISSUE THREAD

**Issue by KinetiCore-Labs** [codeisscience/journal-policy-tracker-frontend#87]
**Describe the bug**
In the header section of the homepage, the button "Read and Sign the manifesto" is not responsive and overflows in the mobile view of the website.

**To Reproduce**

1. Go to 'https://journal-policy-tracker.netlify.app/'
2. Right-click over the "Read and Sign the manifesto" button and click on "Inspect".
3. Check the responsiveness of the website
4. We can see, that the button "Read and Sign the manifesto" is overflowing.

**Expected behavior**
The button should be responsive.

**Screenshots**
![image](https://user-images.githubusercontent.com/57287988/161422436-03eac753-6379-47c8-a917-bae589cd70eb.png)

**Comment by KinetiCore-Labs** [comment]
https://github.com/codeisscience/journal-policy-tracker-frontend/pull/86

I have fixed this issue in this PR.

**Comment by padmajabhol** [comment]
We already have a PR solving this issue, please make sure you aren't creating duplicate issues/PRs. Also its always better to wait for maintainers to assign you an issue before opening a particular PR.
