### ISSUE TITLE
Navbar should be sticky for better user experience

### ISSUE THREAD

**Issue by NumanAnees** [codeisscience/journal-policy-tracker-frontend#88]
## According to the Google
![nav_sticky](https://user-images.githubusercontent.com/67089723/161424064-877b0fea-4acc-4f2c-ba83-ad20d527f744.png)

## Current Behaviour

https://user-images.githubusercontent.com/67089723/161424191-bacd67af-30d4-4464-8a3b-b71247e8e2b2.mp4

## Expected Behaviour

https://user-images.githubusercontent.com/67089723/161425139-b3dd2b1d-fba5-4818-b953-55174689178f.mp4

# Navigation Issue
There is a small navigation issue in the navbar. On clicking the ```code is science``` logo your website should navigate users to Home page. I've not opened a new issue for this because issue is very small. Should I open a new issue?

## Current behaviour
https://user-images.githubusercontent.com/67089723/161425040-a94bf05c-6115-46a7-bb76-97c68bf75ad6.mp4

## Expected Behaviour

https://user-images.githubusercontent.com/67089723/161425210-814f6d61-ecb9-4fbb-a2bc-b1d37ea775e6.mp4

**Comment by NumanAnees** [comment]
@padmajabhol Can you please review it and assign it to me?

**Comment by vedeepika** [comment]
Shall I work on this issue?

**Comment by NumanAnees** [comment]
@vedeepika I've already solved this. Now, just waiting for the maintainers to review it so that I can open a PR.

**Comment by padmajabhol** [comment]
Please do.

**Comment by dikshashukla455** [comment]
Can I work on this issue? @padmajabhol

**Comment by yochannah** [comment]
Thanks @dikshashukla455 - in this case @NumanAnees has already fixed it though :)
