### ISSUE TITLE
Mock up the journal list page [ux/ui task]

### ISSUE THREAD

**Issue by yochannah** [codeisscience/journal-policy-tracker-frontend#9]
We need a nice way to display and filter data like in this form: 
https://docs.google.com/spreadsheets/d/1oY5ak7VJa-qwJJeWA3829S-1akZaYtHuWPYpChBdW2o/edit#gid=1191947390

See also #8

**Comment by pooja-gera** [comment]
Hi, if I understand correctly, you need a UI where the details in the spreadsheet are displayed on a webpage/mobile application?

**Comment by yochannah** [comment]
Correct! No need to worry about the implementation of getting the data -
that's still in development - just they way it would look, plus the ability
to filter down by different values in the columns :)
