### ISSUE TITLE
Navbar not responsive in Home Page

### ISSUE THREAD

**Issue by roshanchatei** [codeisscience/journal-policy-tracker-frontend#91]
### **Describe the bug**
The navbar is not taking the full width for the lower screen size of the browser due to which the other component's responsiveness is affected.

### **Expected behaviour**
The navbar should cover the entire width of the screen

### **Screenshots**
1. Now

![Code is Science - Google Chrome 4_4_2022 6_00_38 AM](https://user-images.githubusercontent.com/83601217/161456734-88ff189c-78dc-4d5a-8763-44a6ca9d3f81.png)

3. Expected

![Code is Science - Google Chrome 4_4_2022 6_11_51 AM](https://user-images.githubusercontent.com/83601217/161456758-fbf1e1ad-f31a-4ad3-adff-20d9aa6fe293.png)

### **To Reproduce**
Steps to reproduce the behaviour:
   1. Go to the home page
   2. Inspect the page
   3.  Go to screen size less than 950px
   
### **Desktop:**

OS: Windows 11
Browser: Chrome
Version: 99

**Comment by roshanchatei** [comment]
@padmajabhol I would like to work on this, can you please assign this to me

**Comment by roshanchatei** [comment]
@ikayz if possible can you close the previous issue of the navbar

**Comment by bharat2913** [comment]
Hi, I would like to work on this issue, can you please assign this to me

**Comment by roshanchatei** [comment]
@padmajabhol assign me this issue, I was working on this issue. The previous issue which I raised was not properly described so I closed it.

For reference #52

**Comment by roshanchatei** [comment]
@padmajabhol?

**Comment by padmajabhol** [comment]
Hi, this issue looks similar to an issue that you created previously #95 
Please avoid creating duplicate issues
