### ISSUE TITLE
Footer headings touch the links

### ISSUE THREAD

**Issue by vedeepika** [codeisscience/journal-policy-tracker-frontend#92]
Thank you for taking the time to file a Feature Request report.

### Problems need to be fixed

The footer headings are touching the upper links. This looks not good and needs to be fixed.

![IMG_20220404_063426](https://user-images.githubusercontent.com/88725279/161458002-783b6858-6092-4c52-9bcc-4bbd19086944.jpg)

### Solution
In the footer area, there must add some space from the top or add some CSS to make the footer heading look good and not touch the links.

**Comment by vedeepika** [comment]
@padmajabhol Can you please review it and assign it to me?

**Comment by padmajabhol** [comment]
Could you be a bit more descriptive? I couldn't exactly understand 😅
