### ISSUE TITLE
Journals page is not responsive and journals form is not in center

### ISSUE THREAD

**Issue by vedeepika** [codeisscience/journal-policy-tracker-frontend#93]
Thank you for taking the time to file a Feature Request report.

### Problems in Journals Page 
On the journal page, the form is not in the center and the heading is also not in the center.

![IMG_20220404_065409](https://user-images.githubusercontent.com/88725279/161459593-7046708d-6952-4e9b-b60d-68f0e1d23d03.jpg)

On the small devices, the page is not responsive. And need to be fixed.

![IMG_20220404_065431](https://user-images.githubusercontent.com/88725279/161459740-2c7e8f1e-0a4a-4e74-a1ed-343743fca4ea.jpg)

**Comment by vedeepika** [comment]
@padmajabhol Can you please review it and assign it to me?

**Comment by roshanchatei** [comment]
@vedeepika This issue has already been raised #91

**Comment by padmajabhol** [comment]
@roshanchatei the issue you are referring to only proposed to make the navbar responsive.

**Comment by vedeepika** [comment]
I fixed all the issues can you please review it #104
