### ISSUE TITLE
Policies Input fields border are overlapping

### ISSUE THREAD

**Issue by roshanchatei** [codeisscience/journal-policy-tracker-frontend#94]
### **Describe the bug**
There are 4 input fields under Policies and there is no margin between them, so when focused on the given border(mainly the bottom border) is being hidden behind the other input field

### **Expected behaviour**
The Input field's border should not overlap.

### **Screenshots**

![Code is Science - Google Chrome 4_4_2022 6_26_31 AM](https://user-images.githubusercontent.com/83601217/161458043-cffd6aea-e350-44aa-83b1-8294926e17df.png)

### **To Reproduce**
Steps to reproduce the behaviour:
   1. Go to the Journals page
   2. 2. Check the Policies input field

### **Desktop:**
OS: Windows 11
Browser: Chrome
Version: 100.0.4896.60

**Comment by roshanchatei** [comment]
@padmajabhol I would like to work on this issue.

**Comment by padmajabhol** [comment]
Go ahead @roshanchatei

**Comment by roshanchatei** [comment]
> Go ahead @roshanchatei

Thank You

**Comment by dikshashukla455** [comment]
Greetings @padmajabhol, Can I work on this issue? As it seems like there is no PR linked to this issue till now.

**Comment by roshanchatei** [comment]
@dikshashukla455 I have done the changes and pushed it, just to make a PR

**Comment by padmajabhol** [comment]
Any updates @roshanchatei ?

**Comment by roshanchatei** [comment]
> Any updates @roshanchatei ?

Just pushing

**Comment by oneknucklehead** [comment]
is this issue still being worked upon? If not, I'd like to work on this.

**Comment by yochannah** [comment]
@roshanchatei just checking in - did you make the PR in the end?

**Comment by roshanchatei** [comment]
@yochannah @padmajabhol can you please review the MR?
And I am sorry for my late response actually, I had messaged @padmajabhol earlier
