### ISSUE TITLE
UI breaks in Mobile view

### ISSUE THREAD

**Issue by roshanchatei** [codeisscience/journal-policy-tracker-frontend#95]
### **Describe the bug**
Many of the code is hardcoded due to which at smaller screen sizes the UI breaks(mainly navbar, footer and some other components). For example width of some components and font size are hardcoded.

### **Expected behaviour**
The components and their children's components should change their attributes at different screen sizes.

### **Screenshots**

![WhatsApp Image 2022-04-04 at 9 08 02 AM](https://user-images.githubusercontent.com/83601217/161470752-fb0793d1-205d-4d3f-859d-90f016cf0e91.jpeg)

![WhatsApp Image 2022-04-04 at 9 08 01 AM](https://user-images.githubusercontent.com/83601217/161470783-b6d181ab-5e8b-4629-a229-36e119c4c432.jpeg)

### **To Reproduce**
Steps to reproduce the behaviour:
   1. Go to Journals, Manifesto, Login or Signup page
   2. Inspect the page
   3. Go to screen size  400px or less

### **Desktop:**
OS: Windows 11
Browser: Chrome
Version: 100.0.4896.60

**Comment by dikshashukla455** [comment]
Can I work on this issue?

**Comment by padmajabhol** [comment]
I guess you had previously created an issue to work on the breaking points #53 . Please avoid creating multiple duplicate issues.
