### ISSUE TITLE
Login - Invalid value passed to property mode in fetch API

### ISSUE THREAD

**Issue by prajwalkulkarni** [codeisscience/journal-policy-tracker-frontend#96]
Thank you for taking the time to file a Bug report.

**Describe the bug**
In the login component, a login handler function takes care of making network calls to the backend using the fetch API. However, this API call is not being triggered because of the invalid value passed to the `mode` property. The current implementation passes `CORS`, but from the fetch API [docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), `CORS` is not a valid option.
The valid options are `no-cors, *cors, same-origin`.  Meaning the value passed to the property is case-sensitive.
The asynchronous results are also handled using Promise chains, which leads to a larger codebase unnecessarily.

**To Reproduce**

1. Go to the Login page (/login)
2. Click on login (You could either enter correct, incorrect, or blank credentials).
3. Before clicking on login open the network tab
4. Click on login, and you'll notice, that no network call is made.

**Expected behavior**
A network request needs to be made corresponding to the information in the fetch API. 
Also migrating from `.then` promise chains to `async/await` would be a good practice that helps in keeping the codebase compact. 

**Screenshots**
`NA`

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 100

**Additional context**

**Comment by prajwalkulkarni** [comment]
@padmajabhol let me know what you think of this. If you could assign this issue to me, I'd be glad to make the necessary changes & getting this fixed. Thanks.

**Comment by padmajabhol** [comment]
This issue could have come under fixing the functionality as proposed under GSOC but I see no harm fixing it right away as a part of contributions. Your thoughts @ikayz ?

**Comment by prajwalkulkarni** [comment]
Yes, that'd work as well, but I was thinking I could address issues that would require implementing more significant changes, be it with styles or validation and development of other components. Anything is fine and I'd be willing to go with the decisions made by mentors and the project maintainers. I was also wondering if there is any template available for writing the project proposal. If yes, where do I find it? Thanks.

**Comment by padmajabhol** [comment]
Yes we do have one.
https://docs.google.com/document/d/1zrHGk1guWboGlOuQKd6aaaplQtGGXChwj_zwOdz9KE0/edit#

**Comment by prajwalkulkarni** [comment]
Thank you. Will use the given template to create my proposal.

**Comment by ikayz** [comment]
@prajwalkulkarni thanks for pointing that out. @padmajabhol yeah that's a good idea. Also do not that the backend currently has issues that need fixing, the backend API isn't working as it should be.
