### ISSUE TITLE
Home page - No link add on Read and Sign the manifesto button

### ISSUE THREAD

**Issue by vedeepika** [codeisscience/journal-policy-tracker-frontend#97]
Thank you for taking the time to file a Feature Request report.

### The issue needs to be fixed

In the home page hero section, there is a button read and sign the manifesto. there is no link added to this button. I think when the user clicks on this button then the page must be redirected to the manifesto page.

![1649067285p-1920x1080](https://user-images.githubusercontent.com/88725279/161525393-a4859079-5ed3-4124-98dd-1e6c564ff98a.jpg)

### How to fix it
I can add the link to the manifesto page on the read and sign the manifesto button (on the home page).

Please assign me this issue to fix.

**Comment by padmajabhol** [comment]
We don't have this feature yet so right now we can't redirect the user anywhere.
