### ISSUE TITLE
Redesigning the footer component

### ISSUE THREAD

**Issue by dikshashukla455** [codeisscience/journal-policy-tracker-frontend#98]
Thank you for taking the time to file a Bug report.

**Describe the bug**
A footer component consists of some bugs:
1) there is no padding between the links.
2) In desktop view, It contains extra empty space from the right-hand side  
3) there is no margin between the icon and text.

**To Reproduce**

1. Go to the Home page
2. Scroll down to the footer section
3. See an error

**Actual behavior**

** Screenshots**
Desktop view:
![Screenshot (1024)](https://user-images.githubusercontent.com/60606998/161592781-dfbe5075-34e4-4d6e-acde-ca5a97f799da.png)

Mobile view:
![Screenshot (1026)](https://user-images.githubusercontent.com/60606998/161592892-98062c17-cf01-4fe1-8208-94b4e2d3674a.png)

**Expected behavior**
1) Added the padding between the links.
2) Added the colors in icons.
3) Added the space between the icon and text.
4) Resolves the empty space.
5) Added the hover transition 

** Screenshots**

Desktop view:

![Screenshot (1027)](https://user-images.githubusercontent.com/60606998/161593018-6062c770-858e-4f34-a058-3007441ac3c4.png)

Mobile view:
![Screenshot (1025)](https://user-images.githubusercontent.com/60606998/161593069-438d8f27-89a5-436b-ad38-6125447c1e24.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Smartphone (please complete the following information):**

- Device:  OnePlus Nord CE
- OS:  Android 11
- Browser: Chrome

**Additional context**
to make it more innovative, I have added the colors in the icons of their logo in the contact section at the footer. Also added a transition in hover effects.

**Comment by dikshashukla455** [comment]
@padmajabhol Can I work on this issue, If it is valid?

**Comment by CIPHERTron** [comment]
Looks good. You can go ahead and open a PR @dikshashukla455 🚀

**Comment by dikshashukla455** [comment]
Okay I will,. Thank you

**Comment by dikshashukla455** [comment]
@CIPHERTron @padmajabhol I have made a PR. Kindly review it. Thank you.
