### ISSUE TITLE
Added the some space in 'Contact us' heading and in Contact us form, Incorrect input type in subject field

### ISSUE THREAD

**Issue by dikshashukla455** [codeisscience/journal-policy-tracker-frontend#99]
Thank you for taking the time to file a Bug report.

**Describe the bug**

The contact page contains several bugs :
1) 'contact us' heading touches the navbar border.
In contact form:
-  In the subject field, it has 'password' in input type instead of the 'text'.
-  In the message field, It has only an input field rather than a textarea.
-  There is no space between the remember me checkbox and the 'send' button.

**To Reproduce**

1. Go to the website (https://journal-policy-tracker.netlify.app/)
2. Click on the Contact link in the navbar
3. Scroll down to the contact form
4. See an error

**Actual behavior**

The bugs you can see in the below image:
**Screenshots**'

![Screenshot (1030)_LI](https://user-images.githubusercontent.com/60606998/161607033-283d92e7-3901-4389-8fa2-13f6f77549b1.jpg)

**Expected behavior**
1) Added some space above the 'contact us' heading.
2) Change the 'subject' input field with text type instead of the password type.
3) Added some space in between the remember me checkbox and the 'send' button.
4) Added the textarea in the 'message' field.

**Screenshots**

![Screenshot (1032)_LI](https://user-images.githubusercontent.com/60606998/161607543-56983cec-ff1f-4e4d-b8a7-39dfc052c8be.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Smartphone (please complete the following information):**

- Device:  OnePlus Nord CE
- OS:  Android 11
- Browser: Chrome

**Comment by dikshashukla455** [comment]
@padmajabhol  Can I work on this issue? If it is valid? Please, Kindly review the above issue. Thank you.

**Comment by padmajabhol** [comment]
Sure, thanks for pointing this out.

**Comment by dikshashukla455** [comment]
Welcome :)
I will make PR for this issue.

**Comment by dikshashukla455** [comment]
Greetings, I have made the PR. kindly review it. Thank you. @padmajabhol

**Comment by dikshashukla455** [comment]
Greetings @padmajabhol, I resolved all the problems and updated the PR. Kindly review it. Thank you

**Comment by yochannah** [comment]
Thanks for the PR @dikshashukla455! We're a bit snowed under with lots of applications and PRs right now, but we'll review this as soon as we get a chance

**Comment by yochannah** [comment]
oh, I lied, Padamaja has already approved - epic!
